### ISSUE TITLE
Power summarizer has wrong values upon app restart

### ISSUE THREAD

**Issue by stiped** [gruijter/com.gruijter.powerhour#79] opened 2022-11-08 21:59 UTC
Hi,

When I restart the application, the values are messed up. See attached screenshot. I'm using version 4.7.6.
The correct values should have been: ~1.75 KWh (this hour), 178.79 KWh (total since I installed the aeotec heavy duty switch).

This behavior applies for all summarizer's I've added, regardless of source.  

Best,
Stian
![power_summarizer](https://user-images.githubusercontent.com/5869881/200684636-9eb60206-6742-4aeb-beb0-93f4ef032557.png)

**Comment by gruijter** [comment] 2022-11-15 18:30
I cannot reproduce this issue.

**Comment by gruijter** [comment] 2022-12-03 11:37
closing this issue. if you have more info on how I can reproduce this myself please reopen.

**Comment by gruijter** [comment] 2022-12-05 12:10
I can reporoduce the issue for summarizers that have 'Watt as source'

**Comment by stiped** [comment] 2022-12-10 18:57
None of my devices uses watt as source. It still ghosts the consumption, even after the update

**Comment by gruijter** [comment] 2022-12-10 19:21
I got confirmation from several people that 4.9.0 solves their ghost usage when using watt as source. So your issue is different then. And I cannot reproduce it, nor explain how your usage is a factor 1000 higher then the source device usage. Please provide details how I can reproduce what you are experiencing.

**Comment by gruijter** [comment] 2023-01-11 09:26
please check latest v5 app. If problem still exists reopen the issue.

**Closed by gruijter** 2023-01-11 09:26 UTC
Labels: bug
